### ISSUE TITLE
System extensions and developer ID

### ISSUE THREAD

**Issue by gopakumarce** [knightsc/sb#2]
This is nothing related to this repo, I just badly wanted to thank you, just dint know how to reach you, so thought I will try this :). I am trying to bootstrap a startup (linkedin.com/in/gopakumarce) for which I was trying to develop a network-extension-systemextension on the mac. The whole area of systemextensions is quite poorly documented and filled with confusions as can be seen in apple developer forums. You had a very good article on system extensions, thanks for that.

 And to top up the systemextension confusion, getting system extension developer id signed and working is a whole another beast. Anyways after a few days of struggle i got it working, except that I ran into this wierd issue that if I install the app in my own laptop it works just fine (regardless of where i place the app in my laptop) whereas in other people's laptop it doesnt work .. All it would say in the logs is 'sysextd: attempting to realize extension" and then just a callback to my app saying sysext failed! I would have gone around in circles for maybe many more days if I had not come up on your slides https://objectivebythesea.com/v3/talks/OBTS_v3_sKnight.pdf - in one of the sides you alluded to the fact that sysext apps have to be placed in /Applications .. I tried that on other's laptops and it works perfectly !! But in my laptop it doesnt matter where I place it, maybe it somehow checks that I am the same developer on the laptop who signed the app ? Dont know! At any rate, thanks a TON for this slide, saved me a few days and a lot of frustration !

**Comment by knightsc** [comment]
Awesome! I'm glad the slides were of some help. If you haven't already checked out Apple's developer forums I found them some what helpful for asking questions around System Extensions as well. Here's to hoping that the documentation continues to improve!
